# This is a basic workflow to help you get started with Actions
name: Scheduled api call

# Controls when the action will run. 
on:
  # Triggers the workflow on every 30 minutes
  schedule:
    - cron: "*/20 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Github Action for curl
      uses: wei/curl@v1.1.1
      with:
        args: -X GET https://arcane-depths-10569.herokuapp.com/tasks
